config/routes.rb
Ratemyrepo::Application.routes.draw do

  get '/signin' => 'sessions#new', :as => :signin
  match '/signout', :to => 'sessions#destroy', :as => :signout
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/failure', :to => 'sessions#failure'

  get '/about' => 'pages#about'

  get '/settings' => 'settings#user', :as => :user_settings
  post '/settings' => 'settings#update_user'
  get '/settings/repos' => 'settings#repos', :as => :repo_settings
  post '/settings/repos' => 'settings#add_repo'

  get '/:username' => 'users#show', :as => :user
  get '/:username/:repo' => 'repos#show', :repo => /[A-Za-z0-9\.\_\-]+?/, :as => :repo

  resources :reviews, :only => [:create,:destroy]

    # post '/:username/:repo' => 'comments#create', :as => :comment, :only => [:create,:destroy]
    # delete '/:username/:repo' => 'comments#destroy', :as => :comment, :only => [:create,:destroy]

  root :to => 'pages#home'

end

app/models/repo.rb
class Repo < ActiveRecord::Base

  belongs_to :user
  has_many :reviews

  attr_accessible :description, :fork, :name, :url

  validates :name, :presence   => true,
                   :uniqueness => true

  def to_param
    name
  end

  def self.scrape_github(user,repo)
    github = Github::Repos.new(user: user.username, repo: repo).get.body
    create! do |r|
      r.user_id     = user.id
      r.name        = repo
      r.description = github['description']
      r.url         = github['html_url']
      r.fork        = github['fork']
    end
  end

  def avg_rating
    if self.reviews.empty?
      "No ratings"
    else
      ratings = self.reviews.map { |r| r.rating }
      ratings.sum / ratings.count
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :repo_id, :user_id, :rating, :comment, :current
  belongs_to :user
  belongs_to :repo

  validates_presence_of :rating
  validates :rating, inclusion: 1..5

  def self.update_and_create review, user
    if Review.where(repo_id: review[:repo_id],user_id: user).exists?
      old = Review.where(repo_id: review[:repo_id],
                         user_id: user).last
      old.current = false
      old.save!

      rev = Review.new review
      rev.user_id = user.id
      rev
    else
      rev = Review.new review
      rev.user_id = user.id
      rev
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :bio, :email, :fullname, :username, :github
  has_many :repos
  has_many :reviews

  def self.create_with_github_auth(auth)
    create! do |user|
      user.uid = auth['uid']
      if auth['info']
        user.username = auth['info']['nickname']
        user.fullname = auth['info']['name']
        user.email    = auth['info']['email']
        user.bio      = auth['info']['bio']
      end
    end
  end

  def to_param
    username
  end

  def github_repos
    Github::Repos.new.list(user: self.username)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  private

    def redirect_back_or default
      redirect_to(session[:return_to] || default)
      clear_return_to
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/repo_controller.rb
class RepoController < ApplicationController
  before_filter :authorize_github

  def index

  end

  private

    def authorize_github
      auth = YAML.load(File.read(Rails.root.join('config', 'github.yml')))[Rails.env]
      @github = Github.new(:client_id => auth['client_id'],
                         :client_secret => auth['client_secret'])
    end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_filter :reviewed

  def show
    @user = User.find_by_username(params[:username])
    @repo = @user.repos.find_by_name(params[:repo])
    @reviews = @repo.reviews.page.per(10).order('created_at desc').
                                          where(current: true)
  end

  private

    def reviewed
      user = User.find_by_username(params[:username])
      repo = user.repos.find_by_name(params[:repo])
      if repo.reviews.where(user_id: current_user).empty?
        @reviewed = false
        @new_review = Review.new
      else
        @reviewed = true
        @new_review = Review.new
        @old_review = repo.reviews.where(user_id: current_user).last
      end
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.update_and_create(params[:review], current_user)
    if @review.save
      render :partial => 'reviews/show',
             :locals  => { :review => @review },
             :layout  => false,
             :status  => :created
    else
      # render :js => "alert('Review not added')"
    end
  end

  def destroy
  end

  private

    def find_repo
      @repo = Repo.find(params[:review][:repo_id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    store_location
    redirect_to '/auth/github'
  end

  def create
    auth_hash = request.env['omniauth.auth']
    user = User.where(:uid => auth_hash['uid']).first ||
           User.create_with_github_auth(auth_hash)
    session[:user_id] = user.id
    redirect_back_or root_url
    flash[:notice] = "Signed in"
  end

  def failure
    redirect_back_or root_url
    flash[:alert] = "Authentication Failed"
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Signed out"
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  helper SessionsHelper

  before_filter :current_user, except: [:update_user]
  before_filter :authenticate

  def show
  end

  def user
  end

  def update_user
    if current_user.update_attributes(params[:user])
      redirect_to settings_url, notice: "Updated settings"
    else
      redirect_to settings_url, alert: "Update failed"
    end
  end

  def repos
    @repo = current_user.repos.build
    @current_repos = current_user.repos

    @repo_names ||= []
    current_user.github_repos.each do |repo|
      @repo_names << repo.name unless @current_repos.map { |r| r['name'] }.include?(repo.name)
    end
  end

  def add_repo
    @repo = Repo.scrape_github(current_user, params[:repo][:name])
    redirect_to repo_path(current_user,@repo), notice: "Repo added"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize_github

  def show
    @user = User.find_by_username(params[:username])
    @repos = Repo.page.per(10).where(:user_id => @user.id)
  end

  private

    def authorize_github
      @github = Github.new(
                  :client_id => GITHUB['client_id'],
                  :client_secret => GITHUB['client_secret'])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

   def title *parts
    unless parts.empty?
      content_for :title do
        (parts << "RateMyRepo").join(" on ")
      end
    end
  end

  #clean this up. should be a stored URL
  def avatar_url user
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=128"
  end

end

app/helpers/repos_helper.rb
module ReposHelper

  def current_user_owns review
    if current_user == review.user
      true
    else
      false
    end
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def review_notes
    if @reviewed
      {comment: @old_review[:comment],
       rating: @old_review[:rating]}
    else
      {comment: "", rating: ""}
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
      false
    end
  end

  def signed_in?
    return true if current_user
  end

  def correct_user?
    @user = User.find(params[:id])
    unless current_user == @user
      redirect_to root_url, alert: "Access denied"
    end
  end

  def authenticate
    if !current_user
      redirect_back_or root_url
      flash[:alert] = 'You need to sign in to access this page'
    else
      true
    end
  end

  private

    def store_location
      session[:return_to] = request.referrer
    end

    def clear_return_to
      session[:return_to] = nil
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<title>
  <%= content_for?(:title) ? yield(:title) : "RateMyRepo" %>
</title>
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">

  <% flash.each do |name, msg| %>
    <div class="container">
      <div class="alert alert-<%= name == :notice ? "success" : "error" %>" data-alert="alert">
        <h4><%= msg %></h4>
      </div>
    </div>
  <% end %>

  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Logo -->
        <%= link_to "RateMyRepo", root_path, class: "brand" %>

      <!-- Right side nave items -->
        <div class="nav-collapse collapse">
          <ul class="nav pull-right">
            <% if signed_in? %>
              <li><%= link_to current_user.username, user_path(@current_user.username), title: "Profile" %></li>
              <li><%= link_to "Settings", settings_path, title: "View Settings" %></li>
              <li><%= link_to "Sign out", signout_path, title: "Sign out" %></li>
            <% else %>
              <li><%= link_to "Sign in", signin_path, title: "Sign in via Github" %></li>
            <% end %>
          </ul>
        </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/header' %>
  </head>
  <body onload="setTimeout(function() {window.scrollTo(0, 1)}, 10)">

    <%= render 'layouts/navigation' %>

    <%= yield %>

    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class='jumbotron'>
  <div class='container'>
    <h2>Rate My Repo</h2>
    <ul>
      <li>Get feedback on your work</li>
      <li>Find out how your code is being used</li>
      <li>More info here</li>
    </ul>
  </div>
</div>
<div class='container'>
  <div class='span9'>
    <ul>
      <li>Top Rated Repos</li>
      <li>Newest Comments</li>
      <li></li>
  </div>
</div>

app/views/repos/show.html.erb
<% title("#{@user.username}/#{@repo.name}") %>
<div class='jumbotron'>
  <div class='container'>
    <div class='repoinfo'>
      <div class='row'>
        <div class='span9 offset1'>
          <h2><%= @user.username %>/<%= @repo.name %></h2>
          <h5><%= @repo.description %></h5>
          <%= @repo.url %><br />
          Rating: <%= @repo.avg_rating %><br />
          First Commit Date<br />
          Last Commit Date<br />
          Number of Commits<br />
          Pull Requests(Open/Closed)<br />
          Issues(Open/Closed)<br />
          Stars<br />
          Forks<br />
        </div>
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class="span8 offset2">
      <% if signed_in? %>
        <h3>Rate this Repo</h3>
        <%= render partial: 'reviews/edit',
                   locals: {
                     new_review: @new_review,
                     old_review: @old_review } %>
      <% else %>
        <h3><%= link_to "Sign in via Github", signin_path %> to Rate this Repo!</h3>
      <% end %>

      <%= paginate @reviews %>
      <%= render partial: 'reviews/show', collection: @reviews, as: :review %>
      <%= paginate @reviews %>

    </div>
  </div>
</div>

app/views/reviews/_edit.html.erb
<div id='review-form'>
  <%= simple_form_for new_review, remote: true do |f| %>
    <%= f.hidden_field :repo_id, value: @repo.id %>
    <%= f.input :rating, collection: 1..5,
                         include_blank: false %>
    <%= f.input :comment, as: :text,
                          input_html: {
                            rows: "2",
                            value: review_notes[:comment] } %>
    <div class="form-actions">
      <%= f.submit 'Rate', class: 'btn btn-primary', disable_with: "Submitting..." %>
    </div>
  <% end %>
</div>

app/views/reviews/_show.html.erb
<div class="review" id="review-<%= review.id %>">
  <hr />
  <% if current_user_owns review %>
    <%= link_to "x", review_path(review), method: :delete, remote: true, confirm: "Are you sure?", disable_with: "x", class: 'close' %>
  <% end %>
  <h4><%= review.user.username %></h4>
  <small>Posted <%= time_ago_in_words(review.updated_at) %> ago</small>
  <p><%= review.rating %></p>
  <p><%= review.comment %></p>
</div>

app/views/settings/_profile.html.erb
<%= simple_form_for current_user, html: { class: 'form-horizontal' }, url: :settings, method: :post do |f| %>
  <fieldset>
    <%= f.input :fullname, label: "Name" %>
    <%= f.input :email %>
    <%= f.input :bio, input_html: {cols: 50, rows: 5} %>

    <div class="form-actions">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/settings/_repos.html.erb
<%= simple_form_for [@current_user,@repo], :html => { :class => 'form-horizontal' }, :url =>{:controller => 'settings', :action => 'add_repo'}, :method => :post do |f| %>
  <%= f.input :name, collection: @repo_names %>
  <div class="form-actions">
    <%= f.submit 'Add', :class => 'btn btn-primary' %>
  </div>
<% end %>
<!-- FIX ME -->
<hr>

<% @current_repos.each do |repo| %>
  <ul>
    <li><%= repo.name %></li>
  </ul>
<% end %>

app/views/settings/index.html.erb
<%= simple_form_for @edit_user, :html => { :class => 'form-horizontal' }, :url => :settings, :method => :post do |f| %>
  <fieldset>
    <%= f.input :fullname, :label => "Name" %>
    <%= f.input :email %>
    <%= f.input :bio, :input_html => { :cols => 50, :rows => 5} %>

    <div class="form-actions">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
  </fieldset>
<% end %>

app/views/settings/repos.html.erb
<%= simple_form_for [current_user,@repo], :html => { :class => 'form-horizontal' }, :url =>{:controller => 'settings', :action => 'add_repo'}, :method => :post do |f| %>
  <%= f.input :name, collection: @repo_names %>
  <div class="form-actions">
    <%= f.submit 'Add', :class => 'btn btn-primary' %>
  </div>
<% end %>
<!-- FIX ME -->
<hr>

<% @current_repos.each do |repo| %>
  <ul>
    <li><%= repo.name %></li>
  </ul>
<% end %>

app/views/settings/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='span9 offset1'>

      <div class='tabbable tabs-left'>
        <ul class='nav nav-tabs'>
          <li class='active'><%= link_to "Profile", '#profile', data: {toggle:'tab'} %></li>
          <li><%= link_to "Repos", '#repos', data: {toggle:'tab'} %></li>
        </ul>
        <div class='tab-content'>
          <div class='tab-pane active' id='profile'>
            <%= render 'profile' %>
          </div>
          <div class='tab-pane' id='repos'>
            <%= render 'repos' %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<% title("#{@user.username}'s profile") %>
<div class='jumbotron'>
  <div class='container'>
    <div class='bio'>
      <div class='row'>
        <div class='span9 offset1'>
          <h2><%= @user.fullname ? @user.fullname : @user.username %></h2>
        </div>
      </div>
      <div class='row'>
        <div class='span2 offset1'>
          <%= image_tag avatar_url(@user) %>
        </div>
        <div class='span8'>
          <dl class='dl-horizontal'>
            <dt>Github:</dt><dd><%= link_to @user.username, "http://github.com/#{@user.username}" %></dd>
            <dt>Bio:</dt><dd><%= @user.bio %></dd>
          </dl>
        </div>
      </div>
    </div>
  </div>
</div>

<div class='container'>
  <div class='row'>
    <div class='span8 offset2 '>
      <h2>Repos</h2>
      <dl>
        <% if @repos.any? %>
	        <%= paginate @repos %>
          <% @repos.each do |repo| %>
            <dt><%= link_to repo.name, repo_path(@user,repo) %></dt>
            <dd><%= repo.description %></dd>
      	    <ul>
      	      <li><%= repo.avg_rating %></li>
      	    </ul>
          <% end %>
	        <%= paginate @repos %>
        <% else %>
          "No repos"
        <% end %>
      </dl>
    </div>
  </div>
</div>